(add-to-list 'load-path (expand-file-name "~/.emacs.d"))
(add-to-list 'load-path (expand-file-name "~/.emacs.d/clojure-mode"))
(add-to-list 'load-path (expand-file-name "~/.emacs.d/haml-mode"))
(add-to-list 'load-path (expand-file-name "~/.emacs.d/php-mode"))
(add-to-list 'load-path (expand-file-name "~/.emacs.d/yaml-mode"))

(require '_general)
(require '_faces_default)
(require '_modes)
(require '_file_types)
