(add-to-list 'load-path (expand-file-name "~/.emacs.d"))
(add-to-list 'load-path (expand-file-name "~/.emacs.d/color-theme"))
(add-to-list 'load-path (expand-file-name "~/.emacs.d/php-mode"))
(add-to-list 'load-path (expand-file-name "~/.emacs.d/yaml-mode"))
(add-to-list 'load-path (expand-file-name "~/.emacs.d/zenburn-emacs"))

(require '_general)
(require '_faces)
(require '_modes)

(require 'ediff)
(require 'ibuffer)
;; (load "nxhtml/autostart.el")
(require 'php-mode)
(require 'tramp)
(require 'vc)
(require 'vc-svn)
(require 'yaml-mode)

(require '_file_types)
